modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="Simple Enhancement"
displayURL="https://modrinth.com/mod/simple-enhancement"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="PlumeJade"
description="This mod adds a variety of engaging combat systems, new biomes, unique materials, gear and weapons. It stays true to the original game style, is lightweight and full of fun. Start your adventure now!"

# Start of user code block mod configuration
# End of user code block mod configuration


# Start of user code block custom mixins
[[mixins]]
config = "simple_enhancement.mixins.json"
# End of user code block custom mixins

[[dependencies.simple_enhancement]]
modId="neoforge"
type="required"
versionRange="[21.1.190,)"
ordering="AFTER"
side="BOTH"

[[dependencies.simple_enhancement]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="AFTER"
side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration
